theme: jekyll-theme-minimal
title: Portfolio - Deploy Website
description: This is the live version of my desktop portfolio version (https://aeon9300.github.io/Portfolio-setup-and-mobile-version-skeleton-2/)